width = 1200
height = 900
margin = 10
std_text_size = 12
border = margin + std_text_size
reduced_width = width - border
reduced_height = height - border
half_width = width // 2
half_height = height // 2
num_lives = 3
init_num_asteroids = 1
min_asteroid_fraction = 0.25
new_asteroids_on_reset = 1
